### PR TITLE
Fixed broken GST reporting for CA

### PR DESCRIPTION
**Pull request by StratISaurus**
Not sure why it wasn't populating the field before, not much different than the PST section that was working. I made a few tweaks and now I can confirm it to be working on my CA account. Other people are welcome to test or clean up my code. 

Fixes https://github.com/philipmulcahy/azad/issues/92

### CODE REVIEW

**Comment by philipmulcahy** [comment]
Cool!

Any chance you could do a "debug scrape dump" and stick it on #92 so we can prevent regression?

Right click on a relevant order link in the table (first column) and there’s a menu item from azad named something debug something. It should cause a json file to be downloaded which contains the three html files that were scraped for that order. I’m keeping the scrapes in a private repo because they can also contain basic information about up to nine more orders (from the index page) and I’ve not gotten around to building a trustworthy sanitising script. In addition we need a list of the correct (expected) values from the order (to be put in a companion json file).

My direct email (best for the json file to avoid leaking personally identifiable info) is ${firstname}@${lastname}family.org


Yours,

Philip

**Comment by LTBComputers** [comment]
Sure, I'll give that a whirl when I get home tonight and send it over.

**Comment by philipmulcahy** [comment]
Hey Joshua!
Any joy on getting the diagnostic dump so I can add a regression test?
Yours,
Philip

**Comment by StratISaurus** [comment]
Hey Philip!

This totally fell off my radar, thanks for the reminder. It’s going to sound dumb, but how do I get the diagnostic dump? I looked through the Git instructions but I don’t think it created the file I was looking for.

Josh

**Comment by philipmulcahy** [comment]
Hi Joshua,

If I recall (in my zombified state), you do the year button thing and wait until the “rich” table displays.
You should be able to right click on the order id link (left column) for the order you want to send me and there’s an azad item in the context menu that has dump or json or diagnostic in its name. If you click on that option, it should whirr, click and then download a file with a json extension.

DO NOT POST THAT FILE ON THE TICKET it will contain lots of detail about the chosen order and some detail about up to 10 other orders (orders are discovered from amazon pages that batch them up). It doesn’t contain your billing address, card details or super valuable details like that, or at least it didn’t last time I used it, and Amazon are pretty good on stuff like that, but it might have delivery addresses.

Instead, mail it directly to me - firstname@lastnamefamily.org <mailto:firstname@lastnamefamily.org>,  e.g. like  john@smithfamily.org <mailto:joe@smithfamily.org> but with my name instead, preferably with the issue link somewhere so I can find it (you will probably get spam filtered!).

I will not share that data with the internet, but I will put it in a private regression testing repo that only a small number (currently two  including me) devs can use to test the extension and prevent bugs recurring.

If we get enough data for it to be worth doing, we can write scripts to strip all of the personally identifying information out of the data set, but getting this right would be tricky unless we have lots of data.

Yours,

Philip

**Comment by ScottMcNay** [comment]
See instructions here:
https://github.com/philipmulcahy/azad/blob/master/README.md

**Comment by philipmulcahy** [comment]
what @ScottMcNay said

**Comment by philipmulcahy** [comment]
new e-mail address for that dump file (shout if you've sent it already and I've missed it): azadextension@gmail.com

**Comment by halorrr** [comment]
Is a dump still needed here? Cause I can provide one as well

**Comment by philipmulcahy** [comment]
@halorrr it'd still be useful - sorry for being so slow to respond!

**Pull request closed without merging**
