### PR TITLE
Integration with EZP Extension

### PR DESCRIPTION
**Pull request by TSN-Admin-RS**
Here are the Changes to AZAD to allow Inter-Extension Communication with EZP's Extension as we discussed. It also changes the way the data is delivered due to the complications that I ran into trying to get the Data from the AZAD generated Blob Download. 
 More information in the email that I'm sending you.
 
Regards!
   Ricardo

### CODE REVIEW

**Comment by TSN-Admin-RS** [comment]
The only thing that I would like to change, but I'm not sure how to do this in Typescript, is to store the Extension ID that requested the information, so to send it back to just that Extension, the current Code Tries to send it to all of my published and my Dev Extension ID's (which is not Optimal.)

If you could add this I would be very grateful (Should be easy but I did not find a "settings.setString or getString" in your code. and I did not want to mess with things too much.)

**Comment by philipmulcahy** [comment]
I’m on the “road" again, but will take a look when I’m back. No messages need to be broadcast from AZAD - I think that we already know the identity of the initiator (your extension) ‘cos we’re filtering on an allowlist of extension IDs - that means we _should_ be able to send the response back only to that extension, even if the response is asynchronous.

**Comment by TSN-Admin-RS** [comment]
Agreed, asynchronous is fine, I set a 5 min timeout, for your code to respond, I think that should be more than enough.

But Storing the Extension ID required much more changes to the code... and I did not feel comfortable doing them. I would be guessing to much.!.!

Good luck in your travels!

Thanks!

**Comment by TSN-Admin-RS** [comment]
I have added the code to store and get the EZP Requesting Extension ID. so it does not broadcast.

Note: if the ID is not found it will broadcast to the 3 whitelisted Extension IDs.

**Comment by TSN-Admin-RS** [comment]
The code should be good to go but give it a quick review, as you could replace the backup broadcasting, to an error message that is commented out if you prefer.

**Pull request merged**
