### PR TITLE
Add support for amazon.es

### PR DESCRIPTION
**Pull request by vHanda**
The order number is not correctly parsed, but at least one gets most of
the important information.

### CODE REVIEW

**Comment by philipmulcahy** [comment]
Thanks.
1) I'll gladly merge this regardless of your response to my question below...
2) What do you mean by parsing the order number? Can I help fix it?
Yours,
Philip

**Comment by vHanda** [comment]
ping

**Comment by philipmulcahy** [comment]
Need a couple of more days - family bereavement… sorry!

**Comment by vHanda** [comment]
Thanks for merging this. 

I'm sorry about your family situation. I hope you're feeling better.

**Pull request merged**
